import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from 'geist/font/sans';
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "whatsPLAN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Important: suppressHydrationWarning to avoid SSR vs client theme-class mismatch
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}